language: node_js
node_js:
 - "stable"

branches:
  only:
    - master

addons:
  chrome: stable


before_script:
  - yarn global add @angular/cli

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

after_success:
  - codecov 

cache:
  npm: true
  directories:
    - node_modules

script:
  - npm install codecov -g
  - ng lint
  - ng test --watch=false 
  - ng build --prod

after_script:
  - nyc report --reporter=html > coverage/coverage.html

  
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: ./dist/opendoors-frontend/
  on: